language: csharp
sudo: enabled
mono: none
dist: xenial
dotnet: 2.2
solution: RegularApi.sln

env:
  global:
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - IMAGE_TAG=$(echo $BRANCH | tr / _)

addons:
  hosts:
    - rabbitmq-host

services:
  - docker 

before_install:
  - sudo chmod +x Scripts/bash/*
  - ./Scripts/bash/prepare-build.sh

after_script:
  - ./Scripts/bash/cleanup-build.sh

stages:
  - tests
  - delivery
    if: branch = master AND tag IS present

jobs:
  include:
  - stage: tests
    script:
      - ./Scripts/bash/unit-tests.sh
  - stage: delivery
    script:
      - ./Scripts/bash/build-docker-image.sh
      - ./Scripts/bash/push-docker-image.sh
